# Generated by Django 5.2 on 2025-05-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_supplies', '0002_officesupplyrequest_delete_officesupplyorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officesupplyrequest',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='officesupplyrequest',
            name='total_cost',
        ),
    ]
