# Generated by Django 5.2 on 2025-05-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_supplies', '0003_remove_officesupplyrequest_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officesupply',
            name='supplier',
        ),
    ]
