# Generated by Django 5.2 on 2025-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_supplies', '0005_officesupply_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officesupply',
            name='unit',
            field=models.CharField(choices=[('units', 'Units'), ('reams', 'Reams'), ('boxes', 'Boxes'), ('pcs', 'Pieces'), ('sets', 'Sets'), ('packs', 'Packs'), ('rolls', 'Rolls'), ('cartridges', 'Cartridges'), ('bottles', 'Bottles')], default='units', max_length=20),
        ),
    ]
