# Generated by Django 5.2 on 2025-05-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_supplies', '0006_alter_officesupply_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesupply',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='officesupply',
            name='reorder_level',
            field=models.PositiveIntegerField(default=5, verbose_name='Low Stock Level'),
        ),
    ]
