# Generated by Django 5.2 on 2025-05-07 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('office_supplies', '0007_officesupply_minimum_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officesupply',
            name='unit',
            field=models.CharField(max_length=50),  # Temporarily convert to CharField
        ),
    ]
