# Generated by Django 5.2 on 2025-05-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_fix_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('restocked', 'Restocked'), ('depleted', 'Depleted'), ('requested', 'Requested'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected')], max_length=20),
        ),
    ]
