# Generated by Django 5.2 on 2025-05-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet_supplies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarysupply',
            name='supplier',
        ),
    ]
