# Generated by Django 5.2 on 2025-05-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_supplies', '0002_remove_veterinarysupply_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarysupply',
            name='critical_stock',
            field=models.PositiveIntegerField(default=5, verbose_name='Reorder Level'),
        ),
    ]
