# Generated by Django 5.2 on 2025-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_supplies', '0003_alter_veterinarysupply_critical_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarysupply',
            name='unit',
            field=models.CharField(choices=[('units', 'Units'), ('boxes', 'Boxes'), ('bottles', 'Bottles'), ('vials', 'Vials'), ('sachets', 'Sachets'), ('pcs', 'Pieces'), ('tablets', 'Tablets'), ('ampoules', 'Ampoules'), ('doses', 'Doses')], default='units', max_length=20),
        ),
    ]
