# Generated by Django 5.2 on 2025-05-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_supplies', '0005_rename_critical_stock_veterinarysupply_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarysupply',
            name='reorder_level',
            field=models.PositiveIntegerField(default=5, verbose_name='Low Stock Level'),
        ),
    ]
