# Generated by Django 5.2 on 2025-05-07 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '__first__'),
        ('vet_supplies', '0006_alter_veterinarysupply_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarysupply',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_supplies', to='inventory.unitmeasure'),
        ),
    ]
