# Generated by Django 5.2 on 2025-05-09 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_supplies', '0012_add_bulk_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vet_supplies.veterinarysupplyrequest')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet_supplies.veterinarysupply')),
            ],
        ),
    ]
